language: c

branches:
  only:
    - master
    - qa

sudo: required
services:
  - docker

before_script:
  # git submodule init && git submodule update  # done automaticall by travis
  - cd dscripts && git checkout master && git pull && cd ..
  - cp conf.sh.default conf.sh
  - dscripts/build.sh -u

script:
  - dscripts/run.sh -ipV /tests/init_sample_config_phoAt.sh
  - dscripts/run.sh -pV  # start slapd in background
  - sleep 2
  - dscripts/exec.sh /tests/init_sample_data_phoAt.sh
  - dscripts/exec.sh /tests/dump_testuser.sh
  - dscripts/exec.sh /tests/authn_testuser.sh
  - dscripts/exec.sh python3.4 /tests/test1.py

after_success:
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || travis_terminate $?;
#  - docker push $IMAGENAME; || travis_terminate $?;
#  - echo "pushed $IMAGENAME to docker hub";
