language: c

branches:
  only:
    - master
    - qa

sudo: required
services:
  - docker

before_script:
  # git submodule init && git submodule update  # done automaticall by travis
  - cd dscripts && git checkout master && git pull && cd ..
  - cp conf.sh.default conf.sh
  - dscripts/build.sh -u

script:
  - dscripts/run.sh -ipV  # will hang
  - dscripts/exec.sh -p /init_sample_config.sh
  - dscripts/exec.sh -p /init_sample_data_eduAt.sh
  - dscripts/exec.sh -p /dump_testuser.sh  # very basic test -> extend

after_success:
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || travis_terminate $?;
#  - docker push $IMAGENAME; || travis_terminate $?;
#  - echo "pushed $IMAGENAME to docker hub";
